name: app_turismo_usuario
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  get: ^4.6.5
  cloud_firestore: ^4.3.1
  equatable: ^2.0.5
  firebase_storage: ^11.0.10
  google_sign_in: ^4.5.1
  google_sign_in_platform_interface: ^1.1.2
  quiver: ^2.1.5
  floating_bottom_navigation_bar: ^1.5.2
  smooth_page_indicator: ^1.0.1
  location: ^4.4.0
  google_maps_flutter: ^2.2.5
  image_picker: ^0.8.8
  transparent_image: ^2.0.1
  bootstrap_icons: ^1.10.5+2
  email_validator: ^2.1.17
  get_it: ^7.2.0
  intl: ^0.18.1
  flutter_speed_dial: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/Img/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Century
      fonts:
        - asset: fonts/Century Gothic.ttf
        - asset: fonts/CenturyGothic.ttf
        - asset: fonts/GOTHIC.TTF
        - asset: fonts/GOTHICB.TTF
        - asset: fonts/GOTHICB0.TTF
        - asset: fonts/GOTHICBI.TTF
        - asset: fonts/GOTHICI.TTF

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
